// apps/expo/.expo/types/router.d.ts
/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/flashes` | `/flashes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/livestreams` | `/livestreams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/music` | `/music`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/podcasts` | `/podcasts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/trending` | `/trending`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/flashes` | `/flashes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/livestreams` | `/livestreams`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/music` | `/music`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/podcasts` | `/podcasts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/trending` | `/trending`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(tabs)'}/flashes${`?${string}` | `#${string}` | ''}` | `/flashes${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(tabs)'}/subscriptions${`?${string}` | `#${string}` | ''}` | `/subscriptions${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/livestreams${`?${string}` | `#${string}` | ''}` | `/livestreams${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/music${`?${string}` | `#${string}` | ''}` | `/music${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/podcasts${`?${string}` | `#${string}` | ''}` | `/podcasts${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/trending${`?${string}` | `#${string}` | ''}` | `/trending${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/flashes` | `/flashes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/livestreams` | `/livestreams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/music` | `/music`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/podcasts` | `/podcasts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/trending` | `/trending`; params?: Router.UnknownInputParams; };
    }
  }
}
