/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/subs` | `/subs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/info` | `/info`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/options` | `/options`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/subs` | `/subs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/info` | `/info`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/options` | `/options`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(tabs)'}/subs${`?${string}` | `#${string}` | ''}` | `/subs${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/info${`?${string}` | `#${string}` | ''}` | `/info${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/options${`?${string}` | `#${string}` | ''}` | `/options${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(tabs)'}/subs` | `/subs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/info` | `/info`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/options` | `/options`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
