// src/Home.tsx
import React from "react";
import { View, Text, StyleSheet } from "react-native";

export function HomePage() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Welcome to the Home Page!</Text>
      <Text>The hamburger menu should now be in the header.</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1, // This is essential!
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 16,
  },
});
// import { View, Text, StyleSheet } from 'react-native';
// import { useColorScheme } from "react-native"

// export function HomePage() {
//   const colorScheme = useColorScheme()

//   return (
//     <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: colorScheme === 'dark' ? '#121212' : '#FFFFFF' }}>
//       <Text style={{ fontSize: 24, marginBottom: 10, color: colorScheme === 'dark' ? 'white' : 'black' }}>
//         Home
//       </Text>
//       <Text style={{ fontSize: 12, color: colorScheme === 'dark' ? 'white' : 'black' }}>
//         This screen was auto-generated by the CLI.
//       </Text>
//     </View>
//   )
// }